name: Issue Event Logging
on:
  issues:
    types: [created, opened, edited, deleted]
jobs: 
  logging-issue-Event:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue Event Detail
        run: echo "ğŸ“ Issue Event: ${{ github.event.action }}"
          echo "ğŸ“Œ Issue Number: ${{ github.event.issue.number }}"
          echo "ğŸ†” Issue ID: ${{ github.event.issue.id }}"
          echo "âœï¸ Issue Title: ${{ github.event.issue.title }}"
          echo "ğŸ“ Issue Body: ${{ github.event.issue.body }}"
          echo "ğŸ‘¤ Issue Author: ${{ github.event.issue.user.login }}"
          echo "ğŸ”— Issue URL: ${{ github.event.issue.html_url }}"


